name: sw
dependencies:
  - python=3.13
  - pip
  - pip:
      - torch==2.7.1
      - numpy==2.3.1
      - pandas
      - tqdm
      - scikit-learn==1.6.1
      - transformers==4.53.0
      - datasets==4.0.0